baseURL = 'https://genffy.com'
languageCode = 'en-us'
title = '进击的页面仔 | Attack on FE-boy'
theme = 'ananke'
# copyright = 'Genffy <a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备2023001307号-1</a>.'
enableRobotsTXT = true
enableEmoji = true
SectionPagesMenu = "main"
resourceDir = "../resources"
googleAnalytics = "G-PQFJ2C7QZN"
# check i18n missing `hugo --printI18nWarnings | grep i18n`
# new post `hugo new content/en/post/test.md`
[languages]
  [languages.en]
    title = "Attach on FE-boy"
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.zh]
    title = "进击的页面仔"
    languageName = "中文"
    weight = 2
    contentDir = "content/zh"

# menu settings 
[menu]
  [[menu.main]]
    weight = 4
    identifier = "post"
    pre = ""
    post = ""
    name = "文章"
    url = "/post/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "category"
    pre = ""
    post = ""
    name = "标签"
    url = "/category/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  commentoEnable = false
  favicon = "images/mbox_avatar.jpeg"

  [[params.ananke_socials]]
    name = "Twitter"
    url = "https://twitter.com/genffy"

  [[params.ananke_socials]]
    name = "Github"
    url = "https://github.com/genffy"