baseURL: "https://genffy.com" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: "进击的页面仔 | Page-boy"
paginate: 10
theme: PaperMod
defaultContentLanguage: zh
resourceDir: ../resources

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
taxonomies:
  category: categories
  tag: tags
  series: series
# permalinks:
#   posts: /:year/:month/:title/

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "EN"
    weight: 1
    title: Page-boy
    contentDir: "content/en"
    params:
      profileMode:
        enabled: true
        title: Page-boy
        imageUrl: "/images/genffy.jpeg"
        imageTitle: genffy
        buttons:
          - name: Archives
            url: archives
          - name: Tags
            url: tags
    menu:
      main:
        - identifier: posts
          name: Posts
          url: posts
          weight: 5
        - identifier: snippet
          name: Snippets
          url: https://logseq.genffy.com/#/page/code-snippet
          weight: 10
        - identifier: algorithm
          name: Algorithm
          url: https://logseq.genffy.com/#/page/algorithm
          weight: 15
        - identifier: about
          name: About
          url: about
  zh:
    weight: 3
    title: 进击的页面仔
    languageName: "ZH"
    contentDir: "content/zh"
    params:
      profileMode:
        enabled: true
        title: 进击的页面仔
        imageUrl: "/images/genffy.jpeg"
        imageTitle: genffy
        buttons:
          - name: 归档
            url: archives
          - name: 标签
            url: tags
    menu:
      main:
        - identifier: posts
          name: 文章
          url: posts
          weight: 5
        - identifier: snippet
          name: 代码片段
          url: https://logseq.genffy.com/#/page/code-snippet
          weight: 10
        - identifier: algorithm
          name: 算法
          url: https://logseq.genffy.com/#/page/algorithm
          weight: 15
        - identifier: about
          name: 关于
          url: about

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Page-boy - https://genffy.com/"
  author: genffy
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments: true
  # images: ["papermod-cover.png"]

  homeInfoParams:
    enabled: false
    Title: genffy
    Content: >
      # TODO

  socialIcons:
    - name: github
      url: "https://github.com/genffy"
    - name: KoFi
      url: "https://ko-fi.com/genffy"
    - name: twitter
      url: "https://twitter.com/genffy"
    - name: discord
      url: "https://discordapp.com/users/6684"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/genffy/genffy/tree/main"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    # disableHLJS: false
    favicon: "/images/genffy.png"
    favicon16x16: "/images/genffy-16.png"
    favicon32x32: "/images/genffy-32.png"
    apple_touch_icon: "/images/genffy.png"
    safari_pinned_tab: "/images/genffy.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
