baseURL = 'https://genffy.com'
languageCode = 'en-us'
title = '进击的页面仔 | Attack on FE-boy'
theme = 'ananke'
enableRobotsTXT = true
enableEmoji = true
SectionPagesMenu = "main"
resourceDir = "../resources"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  commentoEnable = false
  favicon = "images/mbox_avatar.jpeg"

[[params.ananke_socials]]
name = "Twitter"
url = "https://twitter.com/genffy"

[[params.ananke_socials]]
name = "Github"
url = "https://github.com/genffy"