# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.19

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build
      run: hugo --minify

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public

    - name: Prepare SSH
      run: >
        cd ~ && mkdir .ssh &&
        touch ~/.ssh/known_hosts &&
        ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
      env:
        IP: ${{ secrets.ALIYUN_SERVER_HOST }}

    - name: Deploy to aliyun server
      uses: easingthemes/ssh-deploy@main

      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
        ARGS: "-rltgoDzvO --delete --chown=root:root"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
        REMOTE_USER: "root"
        TARGET: "/apps/genffy-out/"
