# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.147.0'
        extended: true

    - name: Build
      run: hugo --minify

    # - name: Prepare SSH
    #   run: >
    #     cd ~ && mkdir .ssh &&
    #     touch ~/.ssh/known_hosts &&
    #     ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
    #   env:
    #     IP: ${{ vars.TENCENT_SERVER_HOST }}

    # - name: Deploy to aliyun server
    #   uses: easingthemes/ssh-deploy@main

    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.TENCENT_SERVER_ACCESS_TOKEN }}
    #     ARGS: "-rltgoDzvO --delete --chown=root:root"
    #     SOURCE: "public/"
    #     REMOTE_HOST: ${{ vars.TENCENT_SERVER_HOST }}
    #     REMOTE_USER: "root"
    #     TARGET: "/opt/apps/genffy-out/"
